version: "2"

exclude_patterns:
  - "**/*.snap"
  - "**/*graphql-types*"
  - "**/__generated__"
  - "**/*.stories.tsx"
  - "**/*.test.tsx"
  - "**/_test.go"
  - "**/*.spec.ts"
  - "**/*.min.js"

checks:
  method-lines:
    enabled: true
    config:
      threshold: 120
  identical-code:
    config:
      threshold: 25
  similar-code:
    config:
      threshold: 50

plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 4
  govet:
    enabled: true
  gofmt:
    enabled: true
