version: "2"

exclude_patterns:
  - "**/*.snap"
  - "**/*graphql-types*"

checks:
  identical-code:
    config:
      threshold: 25
  similar-code:
    config:
      threshold: 50

plugins:
  duplication:
    enabled: true
    config:
      count_threshold: 4
  eslint:
    enabled: true
    channel: eslint-6
    config:
      config: frontend/.eslintrc.js
  govet:
    enabled: true
  gofmt:
    enabled: true